### PR TITLE
Constrain gem versions; remove Gemfile.lock; unmount contentqa app

### PR DESCRIPTION
**Pull request by anarchivist**
* Disable the legacy Content QA dashboard app, since we don't use it much anymore.
* Ensure that RSpec and the `pg` Postgres gem don't get upgraded by accident.
* Remove `Gemfile.lock` to allow for better upgrades for security releases.

### CODE REVIEW

**Comment by markbreedlove** [comment]
Nice not to have delayed_job running anymore.

**Comment by markbreedlove** [comment]
That all looks good to me. Does anyone else want to look?  @AudreyAltman @no-reply

**Comment by no-reply** [comment]
Awesome. 

Do we want to just remove the commented lines? We can always simply revert the merge commit to reintroduce them.

**Comment by anarchivist** [comment]
@no-reply Done; forced push.

**Comment by no-reply** [comment]
:train:

**Comment by markbreedlove** [comment]
All aboard ... shall I merge?

**Pull request merged**
