### PR TITLE
Update to use ElasticSearch for item "fetch"

### PR DESCRIPTION
**Pull request by markbreedlove**
Remove query that used CouchDB for specific-item fetches.  Use
`V1::Searchable#search` instead.

### CODE REVIEW

**Comment by no-reply** [comment]
This looks good to me! I think @anarchivist and/or @AudreyAltman should give a :+1: before merge, since they both know this app better than I do.

**Comment by anarchivist** [comment]
There's one spec failing that wasn't failing before: [`Scenario: Retrieve more than ten items with one call` (starting line 1187 of the Travis build logs)](https://travis-ci.org/dpla/platform/builds/56657713#L1187). I think we should fix this before merging.

**Comment by markbreedlove** [comment]
OK, it's squashed again.  @AudreyAltman or @anarchivist  should probably merge this, if they think it's ready.

**Comment by anarchivist** [comment]
OK, I'm :+1: on this. As I mentioned in Slack, I've included two commits that change the behavior of the builds in Travis:

* efee062 skips the (currently failing) metacharacter scenario in Travis. When the environment variable `TRAVIS` equals `true` (as a string), Cucumber will skip any tests tagged with `@travis-exclude`.
* 8071014 uses the Travis' container-based build infrastructure, which will spin up the tests more quickly. The biggest change to the configuration is how Elasticsearch is installed, deployed, and started.

Please take a look, and someone else can merge if they think it's ready to go.

**Comment by no-reply** [comment]
:rocket: this all checks out for me!

**Pull request merged**
